### PR TITLE
plz make it looks better

### PR DESCRIPTION
**Pull request by sofish**

### CODE REVIEW

**Comment by max-mapper** [comment]
this messes up code blocks:  and the typography changes really arent that much different from the master branch. is there a specific problem you were trying to solve here?

**Comment by sofish** [comment]
just add the new typography css to the style.css, and fixed the nowrap bug on block elements

**Comment by sofish** [comment]
can you remove the `<code>` tag from the `<pre>`.

wrapping bug

BTW. the code is `undefined`.

**Comment by max-mapper** [comment]
what browser are you on? this is what the site looks like google chrome:

**Comment by sofish** [comment]
the userAgent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:14.0) Gecko/20100101 Firefox/14.0.1

it works fine on chrome as your screenshot but not in firefox

**Comment by max-mapper** [comment]
this issue is a duplicate of https://github.com/maxogden/callback-hell/issues/5

**Pull request closed without merging**
