### PR TITLE
Adds an additional benefit of naming functions

### PR DESCRIPTION
**Pull request by c4milo**

### CODE REVIEW

**Comment by welll** [comment]
@c4milo, Do you know if it can be achieved without naming function? Like assign the anonymous function to a variable.

**Comment by c4milo** [comment]
As far as I know, no.

**Comment by welll** [comment]
I don't think that naming functions is the only manner to identify the culprits... Anyway, I can check and make a test using a profiling tool. What do you think?

For example, suppose we have a function waiting a callback arg

``` javascript
function test(err, callback){
...
...
callback();
}
```

I THINK that I can do the code below and the profiling tool will work in the same way:

``` javascript
var x = function(){....};
test(null,x);
```

I think is not necessary creating a naming function like:

``` javascript
function y(){
....
}

test(null,y);
```

**Comment by c4milo** [comment]
Well, I did my own tests using https://github.com/c4milo/node-webkit-agent and the names were not showing up. Maybe I'm missing something.

**Comment by welll** [comment]
@c4milo, I have never used the the node-webkit-agent... Anyway, can you show me how to execute the tests? Do you throw an exception to get the stacktrace?

**Pull request closed without merging**
